CREATE EXTERNAL TABLE IF NOT EXISTS financials_raw.company_balance_sheet (
  report_date DATE,
  symbol STRING,
  period_type STRING,
  current_assets DOUBLE,
  cash_cash_equivalents_and_short_term_investments DOUBLE,
  cash_and_cash_equivalents DOUBLE,
  restricted_cash DOUBLE,
  cash_financial DOUBLE,
  cash_cash_equivalents_and_federal_funds_sold DOUBLE,
  other_short_term_investments DOUBLE,
  trading_securities DOUBLE,
  receivables DOUBLE,
  accounts_receivable DOUBLE,
  gross_accounts_receivable DOUBLE,
  allowance_for_doubtful_accounts_receivable DOUBLE,
  other_receivables DOUBLE,
  taxes_receivable DOUBLE,
  inventory DOUBLE,
  finished_goods DOUBLE,
  work_in_process DOUBLE,
  raw_materials DOUBLE,
  other_inventories DOUBLE,
  prepaid_assets DOUBLE,
  current_deferred_assets DOUBLE,
  assets_held_for_sale_current DOUBLE,
  hedging_assets_current DOUBLE,
  other_current_assets DOUBLE,
  total_non_current_assets DOUBLE,
  net_ppe DOUBLE,
  gross_ppe DOUBLE,
  accumulated_depreciation DOUBLE,
  properties DOUBLE,
  land_and_improvements DOUBLE,
  buildings_and_improvements DOUBLE,
  machinery_furniture_equipment DUOBLE,
  construction_in_progress DOUBLE,
  other_properties DOUBLE,
  investment_properties DOUBLE,
  goodwill_and_other_intangible_assets DOUBLE,
  goodwill DOUBLE,
  other_intangible_assets DOUBLE,
  investments_and_advances DOUBLE,
  investmentin_financial_assets DOUBLE,
  available_for_sale_securities DOUBLE,
  long_term_equity_investment DOUBLE,
  investments_in_other_ventures_under_equity_method DOUBLE,
  investmentsin_subsidiariesat_cost DOUBLE,
  other_investments DOUBLE,
  non_current_deferred_taxes_assets DOUBLE,
  defined_pension_benefit DOUBLE,
  non_current_prepaid_assets DOUBLE,
  non_current_deferred_assets DOUBLE,
  other_non_current_assets DOUBLE,
  total_assets DOUBLE,
  current_liabilities DOUBLE,
  current_debt_and_capital_lease_obligation DOUBLE,
  current_debt DOUBLE,
  current_capital_lease_obligation DOUBLE,
  payables DOUBLE,
  accounts_payable DOUBLE,
  other_payable DOUBLE,
  total_tax_payable DOUBLE,
  current_provisions DOUBLE,
  pensionand_other_post_retirement_benefit_plans_current DOUBLE,
  other_current_liabilities DOUBLE,
  derivative_product_liabilities DOUBLE,
  total_non_current_liabilities_net_minority_interest DOUBLE,
  long_term_debt_and_capital_lease_obligation DOUBLE,
  long_term_debt DOUBLE,
  long_term_capital_lease_obligation DOUBLE,
  non_current_deferred_taxes_liabilities DOUBLE,
  non_current_deferred_revenue DOUBLE,
  non_current_pension_and_other_postretirement_benefit_plans DOUBLE,
  long_term_provisions DOUBLE,
  tradeand_other_payables_non_current DOUBLE,
  other_non_current_liabilities DOUBLE,
  total_liabilities_net_minority_interest DOUBLE,
  net_debt DOUBLE,
  total_debt DOUBLE,
  capital_lease_obligations DOUBLE,
  total_equity_gross_minority_interest DOUBLE,
  stockholders_equity DOUBLE,
  common_stock_equity DOUBLE,
  capital_stock DOUBLE,
  common_stock DOUBLE,
  additional_paid_in_capital DOUBLE,
  share_issued DOUBLE,
  ordinary_shares_number DOUBLE,
  retained_earnings DOUBLE,
  fixed_assets_revaluation_reserve DOUBLE,
  other_equity_interest DOUBLE,
  treasury_stock DOUBLE,
  treasury_shares_number DOUBLE,
  minority_interest DOUBLE,
  total_capitalization DOUBLE,
  tangible_book_value DOUBLE,
  invested_capital DOUBLE,
  working_capital DOUBLE,
  net_tangible_assets DOUBLE
)
PARTITIONED BY (
  provider STRING,
  `exchange` STRING,
  market STRING,
  year INT,
  month INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'separatorChar' = ',',
  'quoteChar'     = '"',
  'escapeChar'    = '\\',
  'skip.header.line.count'='1'
)
STORED AS TEXTFILE
LOCATION '/data/lake/company_balance_sheet/';
