CREATE EXTERNAL TABLE IF NOT EXISTS financials_raw.company_financials (
  report_date DATE,
  symbol STRING,
  period_type STRING,
  total_revenue DOUBLE,
  operating_revenue DOUBLE,
  cost_of_revenue DOUBLE,
  reconciled_cost_of_revenue DOUBLE,
  gross_profit DOUBLE,
  operating_expense DOUBLE,
  selling_general_and_administration DOUBLE,
  general_and_administrative_expense DOUBLE,
  selling_and_marketing_expense DOUBLE,
  research_and_development DOUBLE,
  other_operating_expenses DOUBLE,
  rent_expense_supplemental DOUBLE,
  rent_and_landing_fees DOUBLE,
  depreciation_and_amortization_in_income_statement DOUBLE,
  depreciation_income_statement DOUBLE,
  depreciation_amortization_depletion_income_statement DOUBLE,
  amortization DOUBLE,
  amortization_of_intangibles_income_statement DOUBLE,
  reconciled_depreciation DOUBLE,
  operating_income DOUBLE,
  total_operating_income_as_reported DOUBLE,
  other_income_expense DOUBLE,
  net_interest_income DOUBLE,
  interest_income DOUBLE,
  interest_expense DOUBLE,
  net_non_operating_interest_income_expense DOUBLE,
  interest_income_non_operating DOUBLE,
  interest_expense_non_operating DOUBLE,
  other_non_operating_income_expenses DOUBLE,
  total_other_finance_cost DOUBLE,
  total_unusual_items DOUBLE,
  total_unusual_items_excluding_goodwill DOUBLE,
  special_income_charges DOUBLE,
  other_special_charges DOUBLE,
  write_off DOUBLE,
  restructuring_and_mergern_acquisition DOUBLE,
  impairment_of_capital_assets DOUBLE,
  gain_on_sale_of_ppe DOUBLE,
  gain_on_sale_of_business DOUBLE,
  gain_on_sale_of_security DOUBLE,
  earnings_from_equity_interest DOUBLE,
  pretax_income DOUBLE,
  tax_provision DOUBLE,
  tax_effect_of_unusual_items DOUBLE,
  tax_rate_for_calcs DOUBLE,
  net_income_continuous_operations DOUBLE,
  net_income_from_continuing_operation_net_minority_interest DOUBLE,
  net_income_discontinuous_operations DOUBLE,
  net_income_from_continuing_and_discontinued_operation DOUBLE,
  net_income DOUBLE,
  normalized_income DOUBLE,
  minority_interests DOUBLE,
  net_income_including_noncontrolling_interests DOUBLE,
  otherunder_preferred_stock_dividend DOUBLE,
  net_income_common_stockholders DOUBLE,
  diluted_ni_availto_com_stockholders DOUBLE,
  basic_average_shares DOUBLE,
  diluted_average_shares DOUBLE,
  basic_eps DOUBLE,
  diluted_eps DOUBLE,
  ebitda DOUBLE,
  normalized_ebitda DOUBLE,
  ebit DOUBLE,
  total_expenses DOUBLE
)
PARTITIONED BY (
  provider STRING,
  `exchange` STRING,
  market STRING,
  year INT,
  month INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'separatorChar' = ',',
  'quoteChar'     = '"',
  'escapeChar'    = '\\',
  'skip.header.line.count'='1'
)
STORED AS TEXTFILE
LOCATION '/data/lake/company_financials/';
