CREATE EXTERNAL TABLE IF NOT EXISTS financials_raw.company_cashflow (
  report_date DATE,
  symbol STRING,
  period_type STRING,
  operating_cash_flow DOUBLE,
  net_income_from_continuing_operations DOUBLE,
  depreciation_and_amortization DOUBLE,
  depreciation DOUBLE,
  amortization_cash_flow DOUBLE,
  deferred_tax DOUBLE,
  gain_loss_on_sale_of_ppe DOUBLE,
  gain_loss_on_investment_securities DOUBLE,
  gain_loss_on_sale_of_business DOUBLE,
  net_foreign_currency_exchange_gain_loss DOUBLE,
  stock_based_compensation DOUBLE,
  provisionand_write_offof_assets DOUBLE,
  pension_and_employee_benefit_expense DOUBLE,
  other_non_cash_items DOUBLE,
  change_in_working_capital DOUBLE,
  change_in_receivables DOUBLE,
  change_in_inventory DOUBLE,
  change_in_payable DOUBLE,
  change_in_prepaid_assets DOUBLE,
  change_in_accrued_expense DOUBLE,
  change_in_other_current_assets DOUBLE,
  change_in_other_current_liabilities DOUBLE,
  taxes_refund_paid DOUBLE,
  dividend_received_cfo DOUBLE,
  interest_received_cfo DOUBLE,
  interest_paid_cfo DOUBLE,
  investing_cash_flow DOUBLE,
  capital_expenditure DOUBLE,
  capital_expenditure_reported DOUBLE,
  net_ppe_purchase_and_sale DOUBLE,
  purchase_of_ppe DOUBLE,
  sale_of_ppe DOUBLE,
  net_investment_purchase_and_sale DOUBLE,
  purchase_of_investment DOUBLE,
  sale_of_investment DOUBLE,
  net_investment_properties_purchase_and_sale DOUBLE,
  purchase_of_investment_properties DOUBLE,
  sale_of_investment_properties DOUBLE,
  net_intangibles_purchase_and_sale DOUBLE,
  purchase_of_intangibles DOUBLE,
  sale_of_intangibles DOUBLE,
  net_business_purchase_and_sale DOUBLE,
  purchase_of_business DOUBLE,
  sale_of_business DOUBLE,
  dividends_received_cfi DOUBLE,
  interest_received_cfi DOUBLE,
  net_other_investing_changes DOUBLE,
  financing_cash_flow DOUBLE,
  net_issuance_payments_of_debt DOUBLE,
  issuance_of_debt DOUBLE,
  repayment_of_debt DOUBLE,
  net_long_term_debt_issuance DOUBLE,
  long_term_debt_issuance DOUBLE,
  long_term_debt_payments DOUBLE,
  net_short_term_debt_issuance DOUBLE,
  short_term_debt_issuance DOUBLE,
  short_term_debt_payments DOUBLE,
  net_common_stock_issuance DOUBLE,
  issuance_of_capital_stock DOUBLE,
  common_stock_issuance DOUBLE,
  repurchase_of_capital_stock DOUBLE,
  common_stock_payments DOUBLE,
  cash_dividends_paid DOUBLE,
  common_stock_dividend_paid DOUBLE,
  interest_paid_cff DOUBLE,
  net_other_financing_charges DOUBLE,
  changes_in_cash DOUBLE,
  effect_of_exchange_rate_changes DOUBLE,
  beginning_cash_position DOUBLE,
  end_cash_position DOUBLE,
  other_cash_adjustment_outside_changein_cash DOUBLE,
  free_cash_flow DOUBLE
)
PARTITIONED BY (
  provider STRING,
  exchange STRING,
  market STRING,
  year INT,
  month INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'separatorChar' = ',',
  'quoteChar'     = '"',
  'escapeChar'    = '\\',
  'skip.header.line.count'='1'
)
STORED AS TEXTFILE
LOCATION '/data/lake/company_cashflow/';
