CREATE EXTERNAL TABLE IF NOT EXISTS default.fact_financials_quarterly (
  instrument_key BIGINT,     -- dim_instrument への外部キー
  report_date DATE,          -- 報告日
  
  -- 損益計算書 (financials) の主要なカラム例
  tax_effect_of_unusual_items DOUBLE,
  tax_rate_for_calcs DOUBLE,
  normalized_ebitda DOUBLE,
  total_unusual_items DOUBLE,
  total_unusual_items_excluding_goodwill DOUBLE,
  net_income_from_continuing_operation_net_minority_interest DOUBLE,
  reconciled_depreciation DOUBLE,
  reconciled_cost_of_revenue DOUBLE,
  ebitda DOUBLE,
  ebit DOUBLE,
  net_interest_income DOUBLE,
  interest_expense DOUBLE,
  interest_income DOUBLE,
  normalized_income DOUBLE,
  net_income_from_continuing_and_discontinued_operation DOUBLE,
  total_expenses DOUBLE,
  total_operating_income_as_reported DOUBLE,
  diluted_average_shares DOUBLE,
  basic_average_shares DOUBLE,
  diluted_eps DOUBLE,
  basic_eps DOUBLE,
  diluted_ni_availto_com_stockholders DOUBLE,
  average_dilution_earnings DOUBLE,
  net_income_common_stockholders DOUBLE,
  otherunder_preferred_stock_dividend DOUBLE,
  net_income DOUBLE,
  minority_interests DOUBLE,
  net_income_including_noncontrolling_interests DOUBLE,
  net_income_continuous_operations DOUBLE,
  tax_provision DOUBLE,
  pretax_income DOUBLE,
  other_income_expense DOUBLE,
  other_non_operating_income_expenses DOUBLE,
  earnings_from_equity_interest DOUBLE,
  gain_on_sale_of_security DOUBLE,
  net_non_operating_interest_income_expense DOUBLE,
  total_other_finance_cost DOUBLE,
  interest_expense_non_operating DOUBLE,
  interest_income_non_operating DOUBLE,
  operating_income DOUBLE,
  operating_expense DOUBLE,
  selling_general_and_administration DOUBLE,
  gross_profit DOUBLE,
  cost_of_revenue DOUBLE,
  total_revenue DOUBLE,
  operating_revenue DOUBLE,

  -- 貸借対照表 (balance_sheet) の主要なカラム例 - 順序を修正
  treasury_shares_number DOUBLE,
  ordinary_shares_number DOUBLE,
  share_issued DOUBLE,
  net_debt DOUBLE,
  total_debt DOUBLE,
  tangible_book_value DOUBLE,
  invested_capital DOUBLE,
  working_capital DOUBLE,
  net_tangible_assets DOUBLE,
  capital_lease_obligations DOUBLE,
  common_stock_equity DOUBLE,
  total_capitalization DOUBLE,
  total_equity_gross_minority_interest DOUBLE,
  minority_interest DOUBLE,
  stockholders_equity DOUBLE,
  other_equity_interest DOUBLE,
  treasury_stock DOUBLE,
  retained_earnings DOUBLE,
  additional_paid_in_capital DOUBLE,
  capital_stock DOUBLE,
  common_stock DOUBLE,
  total_liabilities_net_minority_interest DOUBLE,
  total_non_current_liabilities_net_minority_interest DOUBLE,
  other_non_current_liabilities DOUBLE,
  employee_benefits DOUBLE,
  non_current_pension_and_other_postretirement_benefit_plans DOUBLE,
  non_current_deferred_liabilities DOUBLE,
  non_current_deferred_taxes_liabilities DOUBLE,
  long_term_debt_and_capital_lease_obligation DOUBLE,
  long_term_capital_lease_obligation DOUBLE,
  long_term_debt DOUBLE,
  current_liabilities DOUBLE,
  other_current_liabilities DOUBLE,
  current_debt_and_capital_lease_obligation DOUBLE,
  current_capital_lease_obligation DOUBLE,
  current_debt DOUBLE,
  other_current_borrowings DOUBLE,
  commercial_paper DOUBLE,
  payables_and_accrued_expenses DOUBLE,
  current_accrued_expenses DOUBLE,
  payables DOUBLE,
  other_payable DOUBLE,
  total_tax_payable DOUBLE,
  income_tax_payable DOUBLE,
  accounts_payable DOUBLE,
  total_assets DOUBLE,
  total_non_current_assets DOUBLE, -- 順序修正
  other_non_current_assets DOUBLE,
  non_current_deferred_assets DOUBLE,
  non_current_deferred_taxes_assets DOUBLE,
  non_current_accounts_receivable DOUBLE,
  investments_and_advances DOUBLE,
  investmentin_financial_assets DOUBLE,
  available_for_sale_securities DOUBLE,
  long_term_equity_investment DOUBLE,
  investmentsin_joint_venturesat_cost DOUBLE,
  investmentsin_associatesat_cost DOUBLE,
  goodwill_and_other_intangible_assets DOUBLE,
  other_intangible_assets DOUBLE,
  net_ppe DOUBLE,
  accumulated_depreciation DOUBLE,
  gross_ppe DOUBLE,
  construction_in_progress DOUBLE,
  other_properties DOUBLE,
  machinery_furniture_equipment DOUBLE,
  buildings_and_improvements DOUBLE,
  land_and_improvements DOUBLE,
  properties DOUBLE,
  current_assets DOUBLE, -- 順序修正
  other_current_assets DOUBLE,
  inventory DOUBLE,
  finished_goods DOUBLE,
  work_in_process DOUBLE,
  raw_materials DOUBLE,
  receivables DOUBLE,
  receivables_adjustments_allowances DOUBLE,
  other_receivables DOUBLE,
  taxes_receivable DOUBLE,
  accounts_receivable DOUBLE,
  cash_cash_equivalents_and_short_term_investments DOUBLE,
  other_short_term_investments DOUBLE,
  cash_and_cash_equivalents DOUBLE,
  cash_equivalents DOUBLE,
  cash_financial DOUBLE,

  load_timestamp TIMESTAMP
)
PARTITIONED BY (
  statement_type STRING,
  year INT,
  month INT,
  day INT
)
STORED AS PARQUET
LOCATION '/data/warehouse/fact_financials_quarterly/';
