INSERT OVERWRITE TABLE default.fact_financials_quarterly
PARTITION (statement_type, year, month, day)
SELECT
    di.instrument_key,
    to_date(raw.report_date) AS report_date,
    
    -- 損益計算書 (financials) の主要なカラム例
    raw.tax_effect_of_unusual_items,
    raw.tax_rate_for_calcs,
    raw.normalized_ebitda,
    raw.total_unusual_items,
    raw.total_unusual_items_excluding_goodwill,
    raw.net_income_from_continuing_operation_net_minority_interest,
    raw.reconciled_depreciation,
    raw.reconciled_cost_of_revenue,
    raw.ebitda,
    raw.ebit,
    raw.net_interest_income,
    raw.interest_expense,
    raw.interest_income,
    raw.normalized_income,
    raw.net_income_from_continuing_and_discontinued_operation,
    raw.total_expenses,
    raw.total_operating_income_as_reported,
    raw.diluted_average_shares,
    raw.basic_average_shares,
    raw.diluted_eps,
    raw.basic_eps,
    raw.diluted_ni_availto_com_stockholders,
    raw.average_dilution_earnings,
    raw.net_income_common_stockholders,
    raw.otherunder_preferred_stock_dividend,
    raw.net_income,
    raw.minority_interests,
    raw.net_income_including_noncontrolling_interests,
    raw.net_income_continuous_operations,
    raw.tax_provision,
    raw.pretax_income,
    raw.other_income_expense,
    raw.other_non_operating_income_expenses,
    raw.earnings_from_equity_interest,
    raw.gain_on_sale_of_security,
    raw.net_non_operating_interest_income_expense,
    raw.total_other_finance_cost,
    raw.interest_expense_non_operating,
    raw.interest_income_non_operating,
    raw.operating_income,
    raw.operating_expense,
    raw.selling_general_and_administration,
    raw.gross_profit,
    raw.cost_of_revenue,
    raw.total_revenue,
    raw.operating_revenue,

    -- 貸借対照表 (balance_sheet) の主要なカラム例 - 順序を修正
    raw.treasury_shares_number,
    raw.ordinary_shares_number,
    raw.share_issued,
    raw.net_debt,
    raw.total_debt,
    raw.tangible_book_value,
    raw.invested_capital,
    raw.working_capital,
    raw.net_tangible_assets,
    raw.capital_lease_obligations,
    raw.common_stock_equity,
    raw.total_capitalization,
    raw.total_equity_gross_minority_interest,
    raw.minority_interest,
    raw.stockholders_equity,
    raw.other_equity_interest,
    raw.treasury_stock,
    raw.retained_earnings,
    raw.additional_paid_in_capital,
    raw.capital_stock,
    raw.common_stock,
    raw.total_liabilities_net_minority_interest,
    raw.total_non_current_liabilities_net_minority_interest,
    raw.other_non_current_liabilities,
    raw.employee_benefits,
    raw.non_current_pension_and_other_postretirement_benefit_plans,
    raw.non_current_deferred_liabilities,
    raw.non_current_deferred_taxes_liabilities,
    raw.long_term_debt_and_capital_lease_obligation,
    raw.long_term_capital_lease_obligation,
    raw.long_term_debt,
    raw.current_liabilities,
    raw.other_current_liabilities,
    raw.current_debt_and_capital_lease_obligation,
    raw.current_capital_lease_obligation,
    raw.current_debt,
    raw.other_current_borrowings,
    raw.commercial_paper,
    raw.payables_and_accrued_expenses,
    raw.current_accrued_expenses,
    raw.payables,
    raw.other_payable,
    raw.total_tax_payable,
    raw.income_tax_payable,
    raw.accounts_payable,
    raw.total_assets,
    raw.total_non_current_assets,
    raw.other_non_current_assets,
    raw.non_current_deferred_assets,
    raw.non_current_deferred_taxes_assets,
    raw.non_current_accounts_receivable,
    raw.investments_and_advances,
    raw.investmentin_financial_assets,
    raw.available_for_sale_securities,
    raw.long_term_equity_investment,
    raw.investmentsin_joint_venturesat_cost,
    raw.investmentsin_associatesat_cost,
    raw.goodwill_and_other_intangible_assets,
    raw.other_intangible_assets,
    raw.net_ppe,
    raw.accumulated_depreciation,
    raw.gross_ppe,
    raw.construction_in_progress,
    raw.other_properties,
    raw.machinery_furniture_equipment,
    raw.buildings_and_improvements,
    raw.land_and_improvements,
    raw.properties,
    raw.current_assets,
    raw.other_current_assets,
    raw.inventory,
    raw.finished_goods,
    raw.work_in_process,
    raw.raw_materials,
    raw.receivables,
    raw.receivables_adjustments_allowances,
    raw.other_receivables,
    raw.taxes_receivable,
    raw.accounts_payable,
    raw.cash_cash_equivalents_and_short_term_investments,
    raw.other_short_term_investments,
    raw.cash_and_cash_equivalents,
    raw.cash_equivalents,
    raw.cash_financial,

    current_timestamp() AS load_timestamp,
    raw.statement_type,
    CAST(raw.year AS INT) AS year,
    CAST(raw.month AS INT) AS month,
    CAST(raw.day AS INT) AS day
FROM
    default.raw_financial_statements raw
JOIN
    default.dim_instrument di ON raw.symbol = di.symbol AND di.instrument_type = 'stock'
WHERE
    raw.period_type = 'quarterly'
    AND to_date(raw.report_date) >= date '{{ params.prev_week_monday }}'
    AND to_date(raw.report_date) <= date '{{ params.prev_week_friday }}'
